Repository BediBot/BediBot-Rewrite, pull requests merged in 2021-08, with the labels that each got.

#4 Ping Command Update
  src/commands/General/ping.ts
  src/lib/BediEmbed.ts
Labels: enhancement

#53 Purge command
  src/commands/Admin/purge.ts
  src/preconditions/ManageChannelPerms.ts
  src/utils/discordUtil.ts
Labels: enhancement

#59 Say command
  src/commands/Admin/say.ts
Labels: enhancement, good first issue

#228 Add in invite command
  src/commands/General/invite.ts
Labels: enhancement, low-priority
